### ISSUE TITLE
Nested NotifyPropertyChanged and null

### ISSUE THREAD

**Issue by lummoj** [reactiveui/DynamicData#150]
I've just been running some tests with `WhenPropertyChanged` and noticed some unusual behaviour when a nested child property is set to null after it is previously set to a non-null value.

This does not appear to fire off a change, I'm not sure if this is a bug or by design?

Changing `DeeplyNestedNotifyPropertyChangedFixture.cs` and adding an assert `result.Should().Be(null);` to the end of `NotifiesInitialValueAndNullChild` does result in a failing test.

**Comment by lummoj** [comment]
I see now this is handled with the optional fallbackValue func.

That being said I'm still running into a problem when using nested properties and `AutoRefresh(a => a.Child)` when a.Child is set to null it is not refreshing. Whereas it works fine if it swaps to another object.

**Comment by lummoj** [comment]
Okay this I think is a better reproduction, replacing Age on ClassB in the test with Object which can be null:
   ```
         var instance = new ClassA();

            var chain = instance.WhenPropertyChanged(a => a.Child.Object, true);
            object result = null;

            var subscription = chain.Subscribe(notification => result = notification?.Value);

            result.Should().Be(null);
            instance.Child = new ClassB { Object = new object() };

            result.Should().Be(instance.Child.Object);

            instance.Child.Object = null;
            result.Should().Be(null); // this fails
```

**Comment by RolandPheasant** [comment]
Thanks for such a detailed problem report. It has been a while since I have looked at this code so I need to investigate. I will do so as soon as I get a chance.

**Comment by fperez-eypscap** [comment]
Hello, this is still happening in DynamicData 6.13.13

**Comment by glennawatson** [comment]
The PR hasn't been updated in a while so I'm going to close. Would appreciate if someone can update and resubmit. 

Thanks.
