### ISSUE TITLE
TransformAsync deadlock

### ISSUE THREAD

**Issue by Feroks** [reactiveui/DynamicData#157]
I am having an issue with TransformAsync. It gets correctly executed for the first element, but then everything hangs.
I tried the same operation with DynamicTrader example solution. Instead of `Transform `used `.TransformAsync(trade => Task.FromResult(new TradeProxy(trade)))`. Had the same behavior. Am I using it incorrectly?

**Comment by RolandPheasant** [comment]
You are using it correctly although admittedly the feature was an experiment which I later decided was flawed (it's implementation). Since it forms part of the API it should be fixed

**Comment by MagneticLlama** [comment]
Any developments with this?
