### ISSUE TITLE
Update SourceList from UI

### ISSUE THREAD

**Issue by ben1628** [reactiveui/DynamicData#238]
First of all, I'm using winform, and declare the following

        private SourceList<Symbol> _myList { get; set; } = new SourceList<Symbol>();
        private readonly IObservableCollection<Symbol> _targetCollection = new ObservableCollectionExtended<Symbol>();
        public  IObservableCollection<Symbol> TargetCollection => _targetCollection;

        public event PropertyChangedEventHandler PropertyChanged;

And later in the code, I simply

      List<Symbol> myList = vmMwt.LoadList<Symbol>();
            _myList.AddRange(myList);
            _myList.Connect()
               .ObserveOn(RxApp.MainThreadScheduler)
               //.ObserveOnDispatcher()
               .Bind(_targetCollection)
               .Subscribe();

In the UI, the TargetCollection is attached to a grid datasource, which is working.  I can update the item and get notification back in the viewModel using

_myList.Connect()….

However, if I add an item to the grid, _myList is not updated with the new item, of course.

But the _targetCollection is updated with the new item.

My question is

How do I add the new items back to _myList?
or
How do I find out where the new item is?

I believe IObservableCollection will trigger a collectionChanged event, but I am not sure the proper way to do this using ReactiveUI with dynamic Data.

**Comment by Claye-L** [comment]
So to answer your precise question, you can do `_targetCollection.ObserveCollectionChanges()` which will give you an observable of all the changes to "_targetCollection".

However, the problem with the previous method is that you are working backward. The nice thing about sourcelist/sourcecache is to have _targetCollection always be an image of your source list, and not have to work backwards. The way this I usually do this is by not changing `_targetCollection`but instead using a command to gather user input and add it to the sourceList. Sadly i am not familiar with winforms so i can't help you on the specifics, but i think the data grid uses binding in two way mode, so unfortunately its default behavior is to break your nice flow of data. I hope you can find a workaround.

**Comment by ben1628** [comment]
I'm familiar with most UI, if you give me an example of how you do it in your platform, I can easily accomplish the same stuff.  Thanks.

I agree the SourceList should be the master.
