### ISSUE TITLE
How to do join when based on a many to many relationship?

### ISSUE THREAD

**Issue by Claye-L** [reactiveui/DynamicData#239]
Currently, the Join operators support One-to-One with RightJoin, InnerJoin, FullJoin and LeftJoin. 
It supports One-to-Many with the JoinMany versions of the above operators. However I dont know how to do a join when i have a many to many relationship.

Here is my situation: 
I Have two tables (`TLeft` and `TRight`) and a junction table `TJunction` that has a LeftKey and a RightKey. The current operators need the right item to bear the left key, so i need a fix/workaround. Ideally i would want the equivalent of `LeftJoinMany` with the following signature  
`public static IObservable<IChangeSet<TDestination, TLeftKey>> LeftJoinManyToMany<TLeft,TLeftKey, TRight, TRightKey,TJunction, TJunctionKey, TDestination>
        (this IObservable<IChangeSet<TLeft,TLeftKey>> left,
           IObservable<IChangeSet<TRight,TRightKey>> right, 
           IObservable<IChangeSet<TJunction,TJunctionKey>> junction, 
           Func<TJunction, TLeftKey> leftKeySelector,
           Func<TJunction,TRightKey> rightKeySelector,
           Func<TLeftKey, TLeft, IGrouping<TRight, TRightKey, TJunctionKey>, TDestination> resultSelector)`

To Describe what i want to do, it's LeftJoinMany except a junction table is what's actually carrying the left and right key. Maybe there is a simple way but i haven't thought of it.

**Comment by RolandPheasant** [comment]
I have never had to do this before so off the top off my head I am not quite sure.

Would be able to create a very simple model with a basic attempt at what you are trying to do? If you could do something which I can run in unit test code I should be able to advise, or even to extend the API to account for your needs

**Comment by Claye-L** [comment]
I made a [gist](https://gist.github.com/Claye-L/bf5c2a3db3d6d78b874bdc0e53c2e100) of almost a unit test which outlines i hope sufficiently the structure of my data and the functionality i hope to achieve.

**Comment by RolandPheasant** [comment]
The gist is perfect and has enabled me to get my head around the problem. With the following code the unit tests pass.

```cs
// 1.  join item b values with the junction
 var junctionJoinedWithB = _right.Connect()
        .InnerJoin(_junction.Connect(), b => b.ItemBId, (ItemB itemB, Junction junction) => (ItemB: itemB , Junction: junction ));

// 2. group on item a id's and select item b's from the grouped result
_result = junctionJoinedWithB
    .GroupWithImmutableState(j => j.Junction.ItemAId)
    .Transform(groupingByA => new ItemAWithListOfItemB 
    {
        ItemAId = groupingByA.Key,
        CorrespondingItemBs = groupingByA.Items.Select(x => x.ItemB).ToList()
    })
    .AsAggregator();
```

**Comment by Claye-L** [comment]
That's a nice tuple, that's clever. Thanks a lot this is exactly what I needed. Hope i didn't hurt your brain too much.
