### ISSUE TITLE
AddOrUpdate acts like AddOrReplace?

### ISSUE THREAD

**Issue by dsaf** [reactiveui/DynamicData#240]
Should not there be an overload that allows to update the value rather than completely replace it? I  might have an unsorted incoming stream of items with the same ID but different versions. If there was an overload accepting an update function I would be able to take the latest version of the same ID.
This is something `ConcurrentDictionary` provides: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate

I guess the `IEqualityComparer` overload of `SourceCache.AddOrUpdate` could be abused to pass a comparer that will do `revision_current >= revision_new` but it feels weird.

Unless I am supposed to use `ConcurrentDictionary` along with `SourceCache` here by design? What would be the DynamicData ideomatic approach?

**Comment by RolandPheasant** [comment]
You can use this https://gist.github.com/RolandPheasant/3bba5e32f2eefb70c538ce4acabf17cb

**Comment by dsaf** [comment]
@RolandPheasant thank you very much, I will try it now!

Just for my information, you don't believe this belongs to the main package philosophically?

**Comment by dsaf** [comment]
@RolandPheasant thank you, but I don't think it will work. It really needs to happen close to source `SourceCache` rather than consumer `IObservable`. The source needs to stay reliable. If I pick the `TKey` to be `string ID` then the source will have the _last_ incoming version rather than _latest_; if I pick the `TKey` to be `(string ID, long Version)` then the source will be denormalised and `TransformWithInlineUpdate` will not work. This method is however still super-useful for not replacing the whole view-model and some of my need, however the original requirement can only be satisfied by something around `SourceCache`.

**Comment by RolandPheasant** [comment]
Yet another alternative alternative would be to use the edit overload:

```cs
mycache.Edit(innerCache => 
{
   //do some operations on the inner cache e.g
   foreach (var item in myItems)
  {
      var existing = innerCache.Lookup(item .Key);
      if (existing .HasValue)
       {
         //update the original item
       }
      else 
      {
          //add the new item
          innerCache.Add(existingItem);
      }
   }
});
```

This may be what you are looking for

**Comment by dsaf** [comment]
I think there is no such thing as just `Add` method, only `AddOrUpdate` on the `ISourceUpdater` or am I wrong? Additionally would it not be non-atomic and thus not thread-safe?

**Comment by RolandPheasant** [comment]
That is just bad typing.

```cs
      var existing = innerCache.Lookup(item .Key);
      if (existing .HasValue)
       {
         //In place update the of the original item 
           var originaltem = existing.Value;
           existing.PropertyA = item.PropertyA ;
           existing.PropertyB = item.PropertyB ;

         //You may also need to do the following [if properties are used for filtering, sorts, grouping ext]
         innerCache.Refresh(existing);
       }
      else 
      {
          //This is an add as we have checked above
          innerCache.AddOrUpdate(existingItem);
      }
```
This will work, or maybe I am missing the point.

**Comment by dsaf** [comment]
@RolandPheasant now I understand completely, thank you very much for your help!
