### ISSUE TITLE
[BUG] Removing an item from an ObservableList with TrnasformMany and a projection

### ISSUE THREAD

**Issue by dchaib** [reactiveui/DynamicData#264]
**Describe the bug**
As shown in RolandPheasant/DynamicData.Snippets#5, I have set up an `ObservableList` with `TransFormMany` and a projection inside. When I remove an item from the `ObservableList`, it is not removed from the output. It works with an `ObservableCache`.

As Roland guessed, the projected item is not removed from the list because it is not found. I believe the culprit is here: https://github.com/RolandPheasant/DynamicData/blob/67367d0068531a94c9ec8a3e197a0b0055f5eca4/DynamicData/List/ChangeAwareList.cs#L519. The call to IndexOf is not using the equalityComparer passed when using TransformMany. I haven't found a way to pass it properly (yet).

**Steps To Reproduce**
Run the unit tests in https://github.com/RolandPheasant/DynamicData.Snippets.

I'm also happy to send a PR with unit tests here.

**Expected behavior**
The items should be removed from the output.

**Screenshots**
n/a

**Environment**
- OS: Windows
- Version: tested in 6.8 (the issue is still present in the master branch today)
- Device: n/a

**Additional context**

**Comment by glennawatson** [comment]
could use https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.findindex?redirectedfrom=MSDN&view=netframework-4.8#System_Collections_Generic_List_1_FindIndex_System_Predicate__0__ and use the equality comparer

**Comment by dchaib** [comment]
The issue is more how to pass the predicate to `ChangeAwareList` than using it ;-)

**Comment by dchaib** [comment]
I may have found something. If that's OK, I'll submit a PR tomorrow and we can see if I'm headed in the right direction.

**Comment by RolandPheasant** [comment]
A PR is welcome. Thanks

**Comment by dchaib** [comment]
I can confirm that this is fixed in 6.13.1 by #265.
