### ISSUE TITLE
[BUG] DistinctCalculator bug with duplicate items (keys)

### ISSUE THREAD

**Issue by lummoj** [reactiveui/DynamicData#273]
**Describe the bug**
When using DistinctValues() adding the same item or key twice (two sources via Merge), then removing it from one source followed by refreshing or updating it from another source causes a crash (KeyNotFoundException)

The main problem is that the item is removed immediately from the internal cache (_itemCache in DistinctCalculator) when it is removed from source 2. Then when the item is updated or refreshed in source 1 it looks in the cache without checking if it is already in there.

One solution is to 'reference' count the keys just like the values in order to handle duplicate keys as well as values. We need to keep the item in the cache until the last remove in order to compare previous values on update or refresh. I'll have a pull request with this shortly.

**Steps To Reproduce**
1. Merge two sources
2. Apply distinct values
3. Add item A to both source 1 and 2
4. Remove item A from source 2
5. Update or refresh item A on source 1
6. KeyNotFoundException

**Expected behavior**
1. No exception should occur, 
2. No changes pushed out assuming item A value remains unchanged

**Environment**
- OS:       Win10
- Version   6.13.1

**Additional context**
Failing test:
```        
[Fact]
public void DuplicateKeysRefreshAfterRemove()
{
    var source1 = new SourceCache<Person, string>(p => p.Name);
    var source2 = new SourceCache<Person, string>(p => p.Name);

    var person = new Person("Person2", 12);

    var results = source1.Connect().Merge(source2.Connect()).DistinctValues(p => p.Age).AsAggregator();

    source1.AddOrUpdate(person);
    source2.AddOrUpdate(person);
    source2.Remove(person);
    source1.Refresh(person); // would previously throw KeyNotFoundException here

    results.Messages.Should().HaveCount(1);
    results.Data.Items.ShouldAllBeEquivalentTo(new[] {12});

    source1.Remove(person);

    results.Messages.Should().HaveCount(2);
    results.Data.Items.Should().BeEmpty();
}
```

**Comment by RolandPheasant** [comment]
This the perfect problem report. Thanks
