### ISSUE TITLE
[BUG] SourceCache.Sort does not update on data or comparer change

### ISSUE THREAD

**Issue by serpentthegreen** [reactiveui/DynamicData#294]
**Describe the bug**

When using SourceCache.Sort( Observable<IComparer<>> ) , only first value from observable is being used, following values are ignored. Also, data is not sorted correctly upon insert

Seems the issues is

QueryWhenChanged<TObject, TKey, TValue> uses Cache<TObject, TKey> that does not handle data changes except add and remove.

1) [Cache<TObject, TKey>.Clone(IChangeSet<TObject, TKey> changes)](https://github.com/reactiveui/DynamicData/blob/master/src/DynamicData/Cache/Internal/Cache.cs) ignores ChangeReason.Moved changes by design, and changing comparer & data produces these changes;

2) I've tried to set resetThreshold to 1 to trigger reset on each comparer change, but it produces 0 changes and cache does not update.

**Steps To Reproduce**
```
static void Main( string[] args )
{
      SourceCache<int, int> test = new SourceCache<int, int>( _=>_.GetHashCode() );
      
      test.AddOrUpdate( 1 );
      test.AddOrUpdate( 3 );
      test.AddOrUpdate( 2 );

      var sort = Observable.Interval( TimeSpan.FromSeconds( 1 ) )
                             .Select( i =>
                                      {
                                        if( i % 2 == 0 )
                                        {
                                          return SortExpressionComparer<int>
                                           .Ascending( _ => _ );
                                        }

                                        return SortExpressionComparer<int>
                                         .Descending( _ => _ );
                                      } );

      test.Connect( )
          .Sort( sort )
          .ToCollection( )
          .Subscribe( ints => { Console.WriteLine( string.Join( ",", ints.Select( _=>_.ToString() ) ) ); } );
        
      Console.ReadLine( );
}
```

Produces :
1,2,3
1,2,3
1,2,3

```
 static void Main( string[] args )
    {
      SourceCache<int, int> test = new SourceCache<int, int>( _=>_  );
      
      test.AddOrUpdate( 1 );
      test.AddOrUpdate( 4 );
      test.AddOrUpdate( 2 );

      test.Connect( )
          .Sort(SortExpressionComparer<int>.Ascending( _ => _ ) )
          .ToCollection( )
          .Subscribe( ints => { Console.WriteLine( string.Join( ",", ints.Select( _=>_.ToString() ) ) ); } );
        
      test.AddOrUpdate( 3 );
      
      Console.ReadLine( );
    }
```
Produces :
1,2,4
1,2,4,3

**Expected behavior**

1) Expected output to change from 1,2,3 to 3,2,1 and back
2) Expected 1.2.3.4 

**Environment**

- OS:       Windows 10
- Device:   PC
- Version:  6.13.19
- Working Version:  6.13.19

**Additional context**

SourceList is behaving as expected
```
static void Main( string[] args )
    {
      SourceList<int> test = new SourceList<int>( );
      
      test.Add( 1 );
      test.Add( 3 );
      test.Add( 2 );

      var sort = Observable.Interval( TimeSpan.FromSeconds( 1 ) )
                             .Select( i =>
                                      {
                                        if( i % 2 == 0 )
                                        {
                                          return SortExpressionComparer<int>
                                           .Ascending( _ => _ );
                                        }

                                        return SortExpressionComparer<int>
                                         .Descending( _ => _ );
                                      } );

      test.Connect( )
          .Sort( sort )
          .ToCollection( )
          .Subscribe( ints => { Console.WriteLine( string.Join( ",", ints.Select( _=>_.ToString() ) ) ); } );
        
      Console.ReadLine( );
    }
```
Produces:
1,2,3
3,2,1

**Comment by serpentthegreen** [comment]
SortedChangeSet contains SortedItems, that can be used to populate QueryWhenChanged.Run result,

I've made quick hack to test it and it achieves desired result, but there has to be better solution
```
if( changes is SortedChangeSet<TObject, TKey> change )
{
    cache.Clear(  );
    foreach( var pair in change.SortedItems )
    {
        cache.AddOrUpdate( pair.Value, pair.Key );
    }
}
else
{
    cache.Clone(changes);
}
```

**Comment by RolandPheasant** [comment]
```ToSortedCollection()``` was introduced to solve this problem. Have you tried it?

**Comment by serpentthegreen** [comment]
I did   .ToCollection( ) to make the simplest example possible, but I'll keep it in mind, thank you.

I've encountered this behavior binding SourceCache to GUI through BindingList and finding out sorting did not work as expected, so I've made additional observer to see the collection as-is and it did show that collection was not modified.

Do you have any advice how to deal with binding issue ?
I have quite straightforward setup

```
_cache.Connect( )
          .AutoRefreshOnObservable(Reevaluator )
          .Filter(FilterObservable) 
          .Sort(SortObservable) 
          .ObserveOn( RxApp.MainThreadScheduler )
          .Bind( _display_list )
          .Subscribe( )
          .DisposeWith( this );
```

but it's not working with SourceCache, only with SourceList

**Comment by serpentthegreen** [comment]
Nevermind, I found out the reason binding was not working as expexted -- i've passed observable as 
 IObservable<IChangeSet<Key, Value>>, not as  IObservable<ISortedChangeSet<Key, Value>> and it used extension with adapter without move handling,

Sorry that i've bothered you, I'm closing the issue
