### ISSUE TITLE
[Question] Child node filtering when using TransformToTree

### ISSUE THREAD

**Issue by LaborJos** [reactiveui/DynamicData#311]
Filter was applied after seeing # 215 comment.
But the parent does not match the condition of the filter.
So no child nodes matching the condition are visible in the TreeView.

![image](https://user-images.githubusercontent.com/19144210/70210521-3f12d500-1776-11ea-9173-5e932c00583c.png)

![image](https://user-images.githubusercontent.com/19144210/70210530-4508b600-1776-11ea-87ea-8b869619f940.png)

How can I handle this?

**Comment by glennawatson** [comment]
Hi there, 

We ask that questions be asked on StackOverflow or you can join slack. 

Should be just a copy/paste job.

This will allow others to gain from your question in the future more easily.
