### ISSUE TITLE
[BUG] SourceCache Binding does not work (RxUI 10.5.43) - UWP 1909/18362, Msft.NETCore.UWP v6.2.9

### ISSUE THREAD

**Issue by rhy-ama** [reactiveui/DynamicData#312]
**Describe the bug**

On the example of two data models, one ```TestRow``` and another ```TestLayout```, both stored and accessed through a ```SourceCache``` wrapper datastores. 

A ```RowsViewModel``` view model is initialized from the View
```
    public sealed partial class MainPage : Page
    {
        private RowsViewModel rowsViewModel { get; set; }

        public MainPage()
        {
            this.rowsViewModel = new RowsViewModel(new TestStorageService());
            this.InitializeComponent();

            this.Loaded += MainPage_Loaded;
        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            rowsViewModel.Start();
            this.Loaded -= MainPage_Loaded;
        }
    }
```

When the View is loaded, the following method is called inside the ViewModel to check if both datasources are ready (through corresponding ```IObservable<bool>```) and to initialize the binding:

```
        public void Start()
        {
            //monitor initialization and enable bindings once finished
            _datasourcesInitWatchDisposable = new SingleAssignmentDisposable();
            _datasourcesInitWatchDisposable.Disposable = 
                _rows.isInitialized
                    .CombineLatest(_layouts.isInitialized, (rowsStatus, layoutsStatus) => rowsStatus&& layoutsStatus)
                    .StartWith(false)
                    .DistinctUntilChanged()
                    .ObserveOn(Scheduler.Default)  // ----> Observe on another thread as loading takes time
                    .Subscribe(
                        i =>
                        {
                            if (i)
                            {
                                EnableBindings();
                                _datasourcesInitWatchDisposable.Dispose();
                            }
                        });
        }
```

A viewmodel is then initialized and produces a GUI binding in the following form:
```
      private void EnableBindings()
        {
            //monitor intervals list, merge it with layout and bind
            _bindingDisposable = _rows.ObservableObject
                        .Connect()
                        .AutoRefreshOnObservable(p => p.WhenAnyPropertyChanged())
                        .LeftJoin(_layoutDataChangeset, l => l.Id,
                            (id, row, layout) =>
                            {
                                if (layout.HasValue)
                                {
                                    return new GUIModel(row, layout.Value);
                                }
                                else
                                {
                                    //no stored layout for this row
                                    return new GUIModel(row, _layouts.InsertNew(row.Id));
                                }
                            })
                        .Sort(SortExpressionComparer<GUIModel>.Ascending(i => i.Layout.Position))
                        //UI bound model so we need to make sure it is processed on GUI thread
                        .ObserveOnDispatcher()
                        .Bind(Rows)
                        //.DisposeMany() //necessary if IntervalWithLayout disposable
                        .Subscribe();
        }
```

Results in the following exception thrown:

**System.InvalidOperationException: 'No current Window object found to obtain a CoreDispatcher from.'**
```
This exception was originally thrown at this call stack:
    System.Reactive.Concurrency.CoreDispatcherScheduler.Current.get() in CoreDispatcherScheduler.cs
    System.Reactive.Linq.DispatcherObservable.ObserveOnDispatcher<TSource>(System.IObservable<TSource>) in CoreDispatcherObservable.cs
    DispatcherTests.ViewModels.RowsViewModel.EnableBindings() in RowsViewModel.cs
    DispatcherTests.ViewModels.RowsViewModel.Start.AnonymousMethod__10_1(bool) in RowsViewModel.cs
    System.Reactive.AnonymousSafeObserver<T>.OnNext(T) in AnonymousSafeObserver.cs
    System.Reactive.ObserveOnObserverLongRunning<TSource>.Drain() in ScheduledObserver.cs
	System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Steps To Reproduce**

A repository with the V2019 project is here on [rhy-ama/DynamicData-DispatcherTest/](https://github.com/rhy-ama/DynamicData-DispatcherTest/tree/master/DispatcherTests)

View.OnLoad() -> ViewModel.Start() -> ViewModel.EnableBindings()

Start() monitors two observables and then calls EnableBindings().

Notes:

1. Removing ```.ObserveOn(Scheduler.Default)``` from ```Start()``` results in same exception

2. Calling Start() n in View's constructor and 1)  results in same exception

3. Replacing ```.ObserveOn(Scheduler.Default)``` with ```.ObserveOnDispatcher()``` in ```Start()``` **works without exception** both calling Start() from View's constructor and event loop.

4. Wrapping EnableBindings() in a Task as follows also works:

```
        private async void EnableBindings()
        {
            await Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
                    () =>
                    {
                    //monitor intervals list, merge it with layout and bind
                    _bindingDisposable = _rows.ObservableObject
                                .Connect()
                                .AutoRefreshOnObservable(p => p.WhenAnyPropertyChanged())
                                .LeftJoin(_layoutDataChangeset, l => l.Id,
                                    (id, row, layout) =>
                                    {
                                        if (layout.HasValue)
                                        {
                                            return new GUIModel(row, layout.Value);
                                        }
                                        else
                                        {
                                                //no stored layout for this row
                                                return new GUIModel(row, _layouts.InsertNew(row.Id));
                                        }
                                    })
                                .Sort(SortExpressionComparer<GUIModel>.Ascending(i => i.Layout.Position))
                                .ObserveOnDispatcher()
                                .Bind(Rows)
                                //.DisposeMany() //necessary if IntervalWithLayout disposable
                                .Subscribe(); 
                    }).AsTask();
        }
```

**Expected behavior**

Binding should work with the original code. 

I have not seen any documentation that requires to save the Dispatcher when spinning a thread to make sure ObserveOnDispatcher() works from it??

**Screenshots**

non-applicable

**Environment**

- OS:       Windows 10 Ent N 1909
- Version:   VS2019 16.4.0 (latest)
- UWP project target/min version is 1909 (build 18362)
- Microsoft.NETCore.UniversalWindowsPlatform 6.2.9
- ReactiveUI 10.5.43

**Comment by RolandPheasant** [comment]
Rx is thread agnostic.  Dynamic data is based on rx and therefore is also thread agnostic so in no way contributing to the these issues.

**Comment by RolandPheasant** [comment]
> I have not seen any documentation that requires to save the Dispatcher when spinning a thread to make sure ObserveOnDispatcher() works from it??

When I first used rx, I also quickly worked out that ObserveOnDispatcher only works if the current thread has a dispatcher and  is therefore unreliable and best avoided.  If you look at the Dynamic.Trader example as you suggested I capture the dispatcher and make my own scheduler provider. Reactive UI has a similar paradigm and provide RxApp.MainThreadScheduler which gives you dispatcher affinity out of the box.  Additionally ObserveOnDispatcher is best avoided as it does not play well when unit testing i.e. how can the underlying scheduler be swapped out for unit testing

**Comment by rhy-ama** [comment]
@RolandPheasant thank you very much for the prompt reply and this information.

I've suspected that ```ObserveOnDispatcher``` requires the current thread to have a dispatcher. Thank you for the confirmation. I will investigate both the snipplets in the DynamicTrader and RxApp.MainThreadScheduler.
