### ISSUE TITLE
[Question] How to get an empty ChangeSet on Connect() if the cache is empty?

### ISSUE THREAD

**Issue by binaryevents** [reactiveui/DynamicData#313]
Hi,

I store almost all my data in Caches. For the initialisation of some stateful service I get the dependencies using `.ToCollection()`, joining all dependencies using `Observable.CombineLatest()`.
Unfortunately `.Connect()` and  `.Filter()` suppress empty ChangeSets so `.ToCollection()` will not emit a collection on subscription if the Cache is Empty.

My best try so far is to use `.StartWithEmpty()` to get an empty collection on subscription. 
Sadly `.StartWithEmpty()` always gives an empty ChangeSet event if the Cache contains items. So this solution causes `.CombineLatest()` to emit multiple times instead of once on subscribe.

So now to my question: Is there any way to allow the empty ChangeSets on subscription to the Cache? Or does someone know a better solution for this situation?

Thanks,
Robert

**Comment by Claye-L** [comment]
Here is an extension method that does what you asked: Use it instead of `cache.Connect()`:

```cs
public static IObservable<IChangeSet<TObject, TKey>> ConnectAndStartWithEmpty<TObject, TKey>(this IObservableCache<TObject, TKey> cache)
        {
            return Observable.Create<IChangeSet<TObject, TKey>>(observer =>
            {
                if (cache.Count == 0)
                    observer.OnNext(ChangeSet<TObject, TKey>.Empty);
                return cache.Connect().Subscribe(observer.OnNext, observer.OnError, observer.OnCompleted);
            });
        }

```
Here's a quick test to see it fits your demands :
```cs
var emcache = new SourceCache<int, int>(x => x * 2);
var dis0 = emcache.ConnectAndStartWithEmpty().Subscribe(Yolo);
emcache.AddOrUpdate(1);
dis0.Dispose();
var dis1= emcache.ConnectAndStartWithEmpty().Subscribe(Yolo);
dis1.Dispose();
void Yolo(IChangeSet<int, int> t)
{
      Console.WriteLine(t.Count);
 }
``` 

If you need to use the filtering properties of `Connect()` you can easily extend the method to take a predicate function and pass it on.

**Comment by binaryevents** [comment]
That works perfect.
Thank you!
