### ISSUE TITLE
ObservableCollectionExtended SuspendNotifications not notifying changes

### ISSUE THREAD

**Issue by aguahombre** [reactiveui/DynamicData#328]
**Bug**
The ObservableCollectionExtended class SuspendNotifications method only raises a NotifyCollectionChangedAction.Reset on disposal.
It should also raise a NotifyCollectionChangedAction.Add event with any elements in the collection when the SuspendNotifications ends.

**Steps To Reproduce**
Call ObservableCollectionAdaptor.Adapt with a change set with more than refreshThreshold items (default 25) and you will get an empty collection displayed in the UI as the UI will get the NotifyCollectionChangedAction.Reset and clear ItemsControl. It will now be out of sync with the backing collection.

**Expected behavior**
SuspendNotifications  should raise a NotifyCollectionChangedAction.Add event if there are any elements in the collection when the SuspendNotifications ends.

**Screenshots**

**Environment**
- OS:     WIndows 10
- Version:   DynamicData 6.13.9

**Additional context**
Avalonia.ReactiveUI

**Comment by glennawatson** [comment]
Multiple add events is what the suspend notifications is attempting to avoid. Some UI frameworks (wpf/uwp/xam forms) having a reset will avoid a ton of work from the UI if you are doing large enough changes.

**Comment by aguahombre** [comment]
Yes SuspendNotification should group all the changes into one or two notifications: NotifyCollectionChangedAction.Reset, and an optional NotifyCollectionChangedAction.Add.
The implementation doesn't send the Add notification.

```
        public IDisposable SuspendNotifications()
        {
            _suspendCount = true;
            _suspendNotifications = true;

            return Disposable.Create(() =>
            {
                _suspendCount = false;
                _suspendNotifications = false;
                OnPropertyChanged(new PropertyChangedEventArgs("Count"));
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
            });
        }
```

It should be 
```
        public IDisposable SuspendNotifications()
        {
            _suspendCount = true;
            _suspendNotifications = true;

            return Disposable.Create(() =>
            {
                _suspendCount = false;
                _suspendNotifications = false;
                OnPropertyChanged(new PropertyChangedEventArgs("Count"));
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
                if (Count > 0)
                {
                    OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, Items.ToList(), 0));
                }
            });
        }
```

Otherwise the UI will never know that the backing collection has any items.

**Comment by glennawatson** [comment]
Yep, and a lot of UI implementations don't support grouped changes.Eg WPF/UWP will bork when you have more than one in a notification. Most UI will just do a re-evaluation of the items on the screen when a Reset comes along.

**Comment by glennawatson** [comment]
Eg you'll get a exception saying it isn't supported on those two platforms.

**Comment by glennawatson** [comment]
Closing this issue since it's doing what it's supposed to be doing that supports widest range of platforms. Likely more of a UI bug with Avalonia if it can't handle Reset properly.
