### ISSUE TITLE
[Question] Filter performance on large data in datagrid

### ISSUE THREAD

**Issue by PlotlyUser2** [reactiveui/DynamicData#345]
I'm really interested in using the dynamic data package, so I played around couple of days with it a bit...

However, I'm currently facing a performance problem, when I try to filter a large dataset (from 300.000 to 1.5 million rows) within the datagrid control.

I've also created a project here on github for testing purposes: https://github.com/PlotlyUser2/ReactiveDataGridTest

My setup for that is pretty simple: I've a search box and a DataGrid preloaded with a large dataset. 

Snippet:

```
	// For binding to UI
	private readonly ReadOnlyObservableCollection<DataGridViewModel> _itemsBinding;

        public ReadOnlyObservableCollection<DataGridViewModel> TargetCollection => _itemsBinding;

        public MainViewModel(SourceList<DataGridViewModel> _dataList)
        {

            AddSomeRandomData(_dataList);

            var _observableSearchPhrase = this
                .WhenAnyValue(x => x.SearchPhrase)
                .Where(x => !string.IsNullOrEmpty(x) || !string.IsNullOrWhiteSpace(x))
                .DistinctUntilChanged()
                .Select(FilterOnId);

            _dataList.Connect()
                .ObserveOnDispatcher()
                .Filter(_observableSearchPhrase)
                .Bind(out _itemsBinding)
                .DisposeMany()
                .Subscribe();

        }

        private static void AddSomeRandomData(SourceList<DataGridViewModel> _dataList)
        {
            var random = new Random();
            for (int i = 0; i < 300_000; i++)
            {

                var buffer = new byte[random.Next(8, 100)];

                random.NextBytes(buffer);
                string hexData = BitConverter.ToString(buffer);

                var dataGridViewModel = new DataGridViewModel
                {
                    TimeStamp = DateTime.Now.ToString("HH:mm:ss.ffffff"),
                    Id = random.Next(1, 10).ToString(),
                    HexData = hexData
                };

                _dataList.Add(dataGridViewModel);
            }
        }
```

As it can be seen here (tested with 300k items)

![filter](https://user-images.githubusercontent.com/39842435/79669327-120e0e80-81bb-11ea-921d-7f968760fbb3.gif)

it is pretty slow. Also the UI is unresponsible at this time too.

This arises the question, does the Filter operation is slow, especially on the first entry, or does the WPF DataGrid rendering takes so much time? In addition to that, how to write the Filter operation in an asynchronous manner to overcome the UI lag while the filtering task is ongoing. I haven't found any example to it. 

Thanks.

**Comment by Claye-L** [comment]
You can choose what operations run on what thread using ReactiveUI's `ObserveOn` operator

```cs

_dataList.Connect()
                .ObserveOn(RxApp.TaskpoolScheduler) // to run on background thread
                .Filter(_observableSearchPhrase)
                .ObserveOn(RxApp.MainThreadScheduler) //this needed because UI updates need to run on the main thread
                .Bind(out _itemsBinding)
                .DisposeMany()
                .Subscribe();
```

This makes it so the filtering operation will run only on a background thread. 
Another option is to use ReactiveUI's `Throttle` on your search field.
Currently for every character change, the whole filter operation is executed. This can be reduced to ignore rapid changes when the user is typing. this should ensure that the filter is only run once the user is done typing

```cs
var _observableSearchPhrase = this
                .WhenAnyValue(x => x.SearchPhrase)
                .Throttle(TimeSpan.FromMiliseconds(200)) // only propagates changes that occur more than 200 miliseconds apart
                .Where(x => !string.IsNullOrEmpty(x) || !string.IsNullOrWhiteSpace(x))
                .DistinctUntilChanged()
                .Select(FilterOnId);
```

Try a combination of the two to get a gauge of the performance of the library and also, a common problem encountered when making UIs. Hope this helps

**Comment by PlotlyUser2** [comment]
That actually helped a lot, to keep the application responsive! Thanks.

But the performance is still slow, when I load over a million of rows in the DataGrid. In fact, the UI become laggy during the filtering operation. Do I have to go for something like data virtualization?

Also, is there a way to show a simple indeterminate progress bar while the filtering process is active?
