### ISSUE TITLE
FilterController

### ISSUE THREAD

**Issue by pr8x** [reactiveui/DynamicData#350]
I am not able to find `FilterController` ( as described here https://dynamic-data.org/2015/04/22/dynamically-sort-filter-and-page-data/). Was it removed from the project?

**Comment by Claye-L** [comment]
Yes the api has been reworked, and the blog is sadly out of date. 
Instead you can use: 


- FilterController<T> -> Func<T,bool> for static filter OR  IObservable<Func<T,bool>> to change the filter dynamically

- SortController<T> -> IComparer<T> for static sort OR IObservable<IComparer<T>> to change the sorting dynamically
