### ISSUE TITLE
feature: Strong Name for next major version

### ISSUE THREAD

**Issue by david-driscoll** [reactiveui/DynamicData#361]
**Is your feature request related to a problem? Please describe.**
Currently one of the libraries I work on is unable to reference DynamicData due to the lack of a strong name key.  (https://github.com/OmniSharp/csharp-language-server-protocol).  Unfortunately this is a constraint we cannot avoid due to our usage inside the of other microsoft tools (razor tooling, powershell tooling, etc).

**Describe the solution you'd like**
I was wondering if a strong name might be considered for the next major version.  Based on some of the more recent [documentation](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming) it isn't a security risk (except for one note in the docs)

**Describe alternatives you've considered**
I have considered adding a submodule but then if another consumer comes along that does not have the same constraints, and decides to use their own version of dynamic data (or has a dependency on something that had DD as a reference) they will most likely run into pain.  This was not an issue when it was done with MediatR but with all the extension methods I see things going really really badly.

**Describe suggestions on how to achieve the feature**
Create or obtain a snk file (feel free to steal lsp's 😄 ) and add AssemblyOringatorKeyFile to a [common msbuild file (`Build.Directory.props`/`Build.Solution.props`/etc)](https://github.com/OmniSharp/csharp-language-server-protocol/blob/bdec4c73240be52fbb25a81f6ad7d409f77b5215/Directory.Build.props#L13)

**Additional context**
I think dynamic data is awesome and in the context of creating language servers I think it could take things to the next level.  I totally understand if this issue rejected, as I know (from experience) strong naming is a highly contentions issue, with very valid arguments on both sides of the problem.
Also to be clear I'm not asking for ReactiveUI to be strong named, just DynamicData.

Thanks for your time, and thanks for DynamicData! ❤️

**Comment by glennawatson** [comment]
You're going to have a angry @anaisbetts if we add strong signing. Probably best close this one before she sees it.
