### ISSUE TITLE
Sort using BinarySearch require uniqueness

### ISSUE THREAD

**Issue by yexcoffier** [reactiveui/DynamicData#371]
When using Sort with SearchOption = UseBinarySearch on an IObservableList, the Sort method doesn't allow duplicated items. Is there a reason why ?

https://github.com/reactiveui/DynamicData/blob/master/src/DynamicData/List/Internal/Sort.cs
```C#
        private int GetInsertPositionBinary(ChangeAwareList<T> target, T item)
        {
            int index = target.BinarySearch(item, _comparer);
            int insertIndex = ~index;

            //sort is not returning uniqueness
            if (insertIndex < 0)
            {
                throw new SortException("Binary search has been specified, yet the sort does not yield uniqueness");
            }

            return insertIndex;
        }
```

I'm currently using this to sort logs. I'm sorting by timestamp but the timestamp can be the same on different log events.

**Comment by glennawatson** [comment]
This is the same as List.BinarySearch it won't allow duplicates to be handled.

**Comment by yexcoffier** [comment]
Thank you for your answer, but I'm still confused, BinarySearch also works with duplicate.
Why not doing this : 
```C#
        private int GetInsertPositionBinary(ChangeAwareList<T> target, T item)
        {
            int index = target.BinarySearch(item, _comparer);
            return index < 0 ? ~index : index;
        }
```

**Comment by glennawatson** [comment]
Nope. We need to know the element which has changed and binary search returns a item not necessarily the same one each time. 

From the binary search docs for c#

`Duplicate elements are allowed. If the Array contains more than one element equal to value, the method returns the index of only one of the occurrences, and not necessarily the first one.`
