### ISSUE TITLE
[Question] How to change SourceCache key dynamically?

### ISSUE THREAD

**Issue by PlotlyUser2** [reactiveui/DynamicData#387]
Considering this simple example:

    using DynamicData;
    using ReactiveUI;
    using System;
    using System.Collections.ObjectModel;
    using System.Reactive.Linq;
    using System.Threading.Tasks;
    using System.Windows;
    
    namespace WpfApp8
    {
        /// <summary>
        /// Interaction logic for MainWindow.xaml
        /// </summary>
        public partial class MainWindow : Window
        {
            private SourceCache<MyType, int> sourceCacheA;
            private IObservable<IChangeSet<MyType, int>> observable;
    
            private readonly ReadOnlyObservableCollection<MyType> _targetCollection;
            public ReadOnlyObservableCollection<MyType> MyDataSource => _targetCollection;
    
            public MainWindow()
            {
                InitializeComponent();
    
                DataContext = this;
    
                sourceCacheA = new SourceCache<MyType, int>(x => x.AProp);
    
                observable = sourceCacheA.Connect();
    
                observable.ObserveOn(RxApp.MainThreadScheduler).Bind(out _targetCollection).Subscribe();
    
                FillSourceCacheFromThread();
            }
    
            private void FillSourceCacheFromThread()
            {
                Task.Run(async () =>
                {
                    for (int i = 0; i < 1e6; i++)
                    {
                        sourceCacheA.AddOrUpdate(new MyType
                        {
                            AProp = i,
                            BProp = 2
                        });
                        await Task.Delay(2000);
                    }
                });
            }
    
            private void ToggleButton_Checked(object sender, RoutedEventArgs e)
            {
                // if checked, then use the x => x.BProp as Tkey
            }
    
            private void ToggleButton_Unchecked(object sender, RoutedEventArgs e)
            {
                // if checked, then switch back to x => x.AProp as Tkey
            }
        }
    }

**Data class**

    public class MyType : INotifyPropertyChanged
    {
        private int aProp;
        private int bProp;
    
        public int AProp { get => aProp; set { aProp = value; NotifyPropertyChanged(nameof(AProp)); } }
        public int BProp { get => bProp; set { bProp = value; NotifyPropertyChanged(nameof(BProp)); } }
    
        public event PropertyChangedEventHandler PropertyChanged;
    
        private void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

**xaml**

    <Window x:Class="WpfApp8.MainWindow"
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
            xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            xmlns:local="clr-namespace:WpfApp8"
            mc:Ignorable="d"
            Title="MainWindow" Height="450" Width="800">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>
            <ToggleButton Checked="ToggleButton_Checked" Grid.Row="0" Height="50" Width="150" Content="ToggleButton"
                          Unchecked="ToggleButton_Unchecked"/>
            <DataGrid Grid.Row="1" ItemsSource="{Binding MyDataSource}" AutoGenerateColumns="False">
                <DataGrid.Columns>
                    <DataGridTextColumn Header="A" Binding="{Binding AProp}" />
                    <DataGridTextColumn Header="B" Binding="{Binding BProp}"/>
                </DataGrid.Columns>
            </DataGrid>
        </Grid>
    </Window>

My goal is to change the `TKey` of the `SourceCache` class in a dynamic manner by clicking the toogle button and therefore to change the update behavior in the view because the key is not unique then. So basically, I want to create a kind of "standing view" and thus maitaining both observables.

Is that possible? If not, what would be an other alternative to achieve the same thing using rx and dynamic data?

**Comment by RolandPheasant** [comment]
The key can only be changed statically using `ChangeKey`.  I cannot think of any obvious means of dynamically switching keys apart from using a 2 cache solution.

**Comment by PlotlyUser2** [comment]
Thanks for your reply.

> The key can only be changed statically using `ChangeKey`. I cannot think of any obvious means of dynamically switching keys apart from using a 2 cache solution.

Basically this:

`observableA.ChangeKey(x => x.BProp)`

Ok.... and how to bring this change to UI, because I don't see any changes brought by `ChangeKey`?

Let's say I'd use the second `SourceCache`, but with a different key. How would be then the change between these two observables happen? 

So, my program would look like this:

```
using DynamicData;
using ReactiveUI;
using System;
using System.Collections.ObjectModel;
using System.Reactive.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace WpfApp8
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private SourceCache<MyType, int> sourceCacheA;
        private SourceCache<MyType, int> sourceCacheB;
        private IObservable<IChangeSet<MyType, int>> observableA;
        private IObservable<IChangeSet<MyType, int>> observableB;

        private ReadOnlyObservableCollection<MyType> _targetCollection;
        public ReadOnlyObservableCollection<MyType> MyDataSource => _targetCollection;

        public MainWindow()
        {
            InitializeComponent();

            DataContext = this;

            sourceCacheA = new SourceCache<MyType, int>(x => x.AProp);
            sourceCacheB = new SourceCache<MyType, int>(x => x.BProp);

            observableA = sourceCacheA.Connect();
            observableB = sourceCacheB.Connect();

            observableA.ObserveOn(RxApp.MainThreadScheduler).Bind(out _targetCollection).Subscribe();

            FillSourceCacheFromThread();
        }

        private void FillSourceCacheFromThread()
        {
            Task.Run(async () =>
            {
                for (int i = 0; i < 1e6; i++)
                {
                    sourceCacheA.AddOrUpdate(new MyType
                    {
                        AProp = i,
                        BProp = 2
                    });
                    sourceCacheB.AddOrUpdate(new MyType
                    {
                        AProp = i,
                        BProp = 2
                    });
                    await Task.Delay(1000);
                }
            });
        }

        private void ToggleButton_Checked(object sender, RoutedEventArgs e)
        {
            // How to "switch" the current observableA to observableB dynamically?
            
        }

        private void ToggleButton_Unchecked(object sender, RoutedEventArgs e)
        {
            // How to "switch" the different observableB to observableA dynamically?

        }
    }
}

```

However, if both Source Caches would contain a million of items, then the "switch" would probably cause some performance problems, or wouldn't it?

I'd very pleased if you can provide a small example based on mine.

**Comment by Claye-L** [comment]
I just dont understand what changing the key has to do with changing the UI. What change do you wanna see propagated to the UI that's ONLY representable by changing the key?

**Comment by PlotlyUser2** [comment]
> I just dont understand what changing the key has to do with changing the UI. What change do you wanna see propagated to the UI that's ONLY representable by changing the key?

Well... Let me try to explain it differently. So, the resulting AddOrUpdate operation from backgroud thread from my example does the following:

AProp | BProp 
_______________
    0     |     2
    1     |     2
    2     |     2
    3     |     2
    4     |     2

if the SourceCache had the key BProp, then the DataDrid would simply contain one row, where the AProp column is updated, which is actually the sense of AddOrUpdate operation, right?

AProp | BProp 
_______________
    x     |     2

x is 0, 1, 2, .... n +1

Now, the purpose of the toggle button, is to change the current observable content, which will be propagated to UI. This kind switch is what I'd like to achieve. And I don't know how...

The real life example would be something what Vector CanOe software does:

https://assets.vector.com/cms/content/products/VectorCAST/Events/TechNights/CANalyzer_QuickStart.pdf

![image](https://user-images.githubusercontent.com/39842435/89444679-5e716000-d752-11ea-936c-7ede29e242ca.png)
