### ISSUE TITLE
Sum aggregates nullable to non-nullable

### ISSUE THREAD

**Issue by dsaf** [reactiveui/DynamicData#46]
Shouldn't `null` + `null` be `null` and not `0`?

``` csharp
public static IObservable<Decimal> Sum<T>(this IObservable<IChangeSet<T>> source, Func<T, Decimal> valueSelector) {...}

public static IObservable<Decimal> Sum<T>(this IObservable<IChangeSet<T>> source, Func<T, Decimal?> valueSelector) {...}
```

The overload 2 can be covered by `valueSelector` when using overload 1. The `null` sum scenario however is impossible at the moment.

**Comment by RolandPheasant** [comment]
That's a fair point.

I will take a look at it as soon  as i can,  unless of course you would like to contribute?

**Comment by dsaf** [comment]
I am a basic ```git``` user, but I will try to see how easy Microsoft made it for people like me in VS 2015.

**Comment by RolandPheasant** [comment]
Github for Windows combined with the visual studio add in are excellent tools for the job

**Comment by dsaf** [comment]
No need for this anymore.
